# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09c14bec3afc3d6f68b48e04cc56da72ea0c27805b9e2f4f1bb353c9db934ab3cccf56186b38d6635e229691e908413149a5a584e20518880e0cac84871de91c

test:
  secret_key_base: 6f8dcde28df002cda251d4a0d515da2ae7fe590e10ddaffddef3630062c73f6364d3dd849b5d26c20f6d56c5bfaee5bf309c41b0bba9a629553aea3dbe6031de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
